// Code generated by protoc-gen-go.
// source: godiscogs.proto
// DO NOT EDIT!

/*
Package godiscogs is a generated protocol buffer package.

It is generated from these files:
	godiscogs.proto

It has these top-level messages:
	Label
	Folder
	Artist
	Image
	Release
*/
package godiscogs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Label struct {
	// The name of the label
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Label) Reset()                    { *m = Label{} }
func (m *Label) String() string            { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()               {}
func (*Label) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Folder struct {
	// The id number of the folder
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// The name of the folder
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Folder) Reset()                    { *m = Folder{} }
func (m *Folder) String() string            { return proto.CompactTextString(m) }
func (*Folder) ProtoMessage()               {}
func (*Folder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Artist struct {
	// The id number of the artist
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// The name of the artist
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Artist) Reset()                    { *m = Artist{} }
func (m *Artist) String() string            { return proto.CompactTextString(m) }
func (*Artist) ProtoMessage()               {}
func (*Artist) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Image struct {
	// The uri to the image
	Uri string `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	// The type of image
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (m *Image) Reset()                    { *m = Image{} }
func (m *Image) String() string            { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()               {}
func (*Image) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Release struct {
	// The id number of the release
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// The title of the release
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	// Artists associated with the release
	Artists []*Artist `protobuf:"bytes,3,rep,name=artists" json:"artists,omitempty"`
	// The folder in which the record is stored
	FolderId int32 `protobuf:"varint,4,opt,name=folder_id,json=folderId" json:"folder_id,omitempty"`
	// Images associated with the release
	Images []*Image `protobuf:"bytes,5,rep,name=images" json:"images,omitempty"`
	// The instance id of this release
	InstanceId int32 `protobuf:"varint,6,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	// The labels connected to this release
	Labels []*Label `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
}

func (m *Release) Reset()                    { *m = Release{} }
func (m *Release) String() string            { return proto.CompactTextString(m) }
func (*Release) ProtoMessage()               {}
func (*Release) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Release) GetArtists() []*Artist {
	if m != nil {
		return m.Artists
	}
	return nil
}

func (m *Release) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Release) GetLabels() []*Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

func init() {
	proto.RegisterType((*Label)(nil), "godiscogs.Label")
	proto.RegisterType((*Folder)(nil), "godiscogs.Folder")
	proto.RegisterType((*Artist)(nil), "godiscogs.Artist")
	proto.RegisterType((*Image)(nil), "godiscogs.Image")
	proto.RegisterType((*Release)(nil), "godiscogs.Release")
}

func init() { proto.RegisterFile("godiscogs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0xa6, 0x4e, 0xc8, 0x55, 0x82, 0x72, 0x62, 0x88, 0xd4, 0x81, 0x2a, 0x53, 0x24,
	0xa0, 0x03, 0x3c, 0x01, 0x0b, 0x52, 0x25, 0x26, 0xbf, 0x00, 0x72, 0x1b, 0x13, 0x59, 0x72, 0xe3,
	0x2a, 0x67, 0x06, 0x5e, 0x9a, 0x67, 0xa0, 0x3e, 0x27, 0x01, 0xd4, 0x85, 0xed, 0xcf, 0xdd, 0x9f,
	0xcf, 0xff, 0xdd, 0xc1, 0x55, 0xeb, 0x1a, 0x43, 0x7b, 0xd7, 0xd2, 0xe6, 0xd8, 0x3b, 0xef, 0xb0,
	0x98, 0x0a, 0xd5, 0x0a, 0xc4, 0xab, 0xda, 0x69, 0x8b, 0x08, 0xf3, 0x4e, 0x1d, 0x74, 0x99, 0xac,
	0x93, 0xba, 0x90, 0xac, 0xab, 0x7b, 0xc8, 0x5e, 0x9c, 0x6d, 0x74, 0x8f, 0x97, 0x30, 0x33, 0x0d,
	0xf7, 0x84, 0x3c, 0xa9, 0xc9, 0x3d, 0xfb, 0xeb, 0x7e, 0xee, 0xbd, 0x21, 0xff, 0x2f, 0xf7, 0x03,
	0x88, 0xed, 0x41, 0xb5, 0x1a, 0x97, 0x90, 0x7e, 0xf4, 0x66, 0x78, 0x37, 0xc8, 0x60, 0xf7, 0x9f,
	0xc7, 0xc9, 0x1e, 0x74, 0xf5, 0x95, 0x40, 0x2e, 0xb5, 0xd5, 0x8a, 0xf4, 0x19, 0xfe, 0x06, 0x84,
	0x37, 0xde, 0x8e, 0x3f, 0xc4, 0x0f, 0xbc, 0x83, 0x5c, 0x71, 0x1c, 0x2a, 0xd3, 0x75, 0x5a, 0x2f,
	0x1e, 0xaf, 0x37, 0x3f, 0x7b, 0x88, 0x41, 0xe5, 0xe8, 0xc0, 0x15, 0x14, 0xef, 0x3c, 0xe9, 0xdb,
	0x89, 0x3c, 0x67, 0xf2, 0x45, 0x2c, 0x6c, 0x1b, 0xac, 0x21, 0x33, 0x21, 0x2a, 0x95, 0x82, 0x41,
	0xcb, 0x5f, 0x20, 0x9e, 0x41, 0x0e, 0x7d, 0xbc, 0x85, 0x85, 0xe9, 0xc8, 0xab, 0x6e, 0xaf, 0x03,
	0x28, 0x63, 0x10, 0x8c, 0xa5, 0x88, 0xb2, 0x61, 0xdd, 0x54, 0xe6, 0x67, 0x28, 0xbe, 0x83, 0x1c,
	0xfa, 0xbb, 0x8c, 0x4f, 0xf5, 0xf4, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x01, 0xfd, 0x80, 0xc6, 0xbd,
	0x01, 0x00, 0x00,
}
