// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: godiscogs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaleState int32

const (
	SaleState_NOT_FOR_SALE SaleState = 0
	SaleState_FOR_SALE     SaleState = 1
	SaleState_SOLD         SaleState = 2
	SaleState_EXPIRED      SaleState = 3
	SaleState_SOLD_OFFLINE SaleState = 4
)

// Enum value maps for SaleState.
var (
	SaleState_name = map[int32]string{
		0: "NOT_FOR_SALE",
		1: "FOR_SALE",
		2: "SOLD",
		3: "EXPIRED",
		4: "SOLD_OFFLINE",
	}
	SaleState_value = map[string]int32{
		"NOT_FOR_SALE": 0,
		"FOR_SALE":     1,
		"SOLD":         2,
		"EXPIRED":      3,
		"SOLD_OFFLINE": 4,
	}
)

func (x SaleState) Enum() *SaleState {
	p := new(SaleState)
	*p = x
	return p
}

func (x SaleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SaleState) Descriptor() protoreflect.EnumDescriptor {
	return file_godiscogs_proto_enumTypes[0].Descriptor()
}

func (SaleState) Type() protoreflect.EnumType {
	return &file_godiscogs_proto_enumTypes[0]
}

func (x SaleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SaleState.Descriptor instead.
func (SaleState) EnumDescriptor() ([]byte, []int) {
	return file_godiscogs_proto_rawDescGZIP(), []int{0}
}

type Track_TrackType int32

const (
	Track_UNKNOWN Track_TrackType = 0
	Track_TRACK   Track_TrackType = 1
	Track_HEADING Track_TrackType = 2
)

// Enum value maps for Track_TrackType.
var (
	Track_TrackType_name = map[int32]string{
		0: "UNKNOWN",
		1: "TRACK",
		2: "HEADING",
	}
	Track_TrackType_value = map[string]int32{
		"UNKNOWN": 0,
		"TRACK":   1,
		"HEADING": 2,
	}
)

func (x Track_TrackType) Enum() *Track_TrackType {
	p := new(Track_TrackType)
	*p = x
	return p
}

func (x Track_TrackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Track_TrackType) Descriptor() protoreflect.EnumDescriptor {
	return file_godiscogs_proto_enumTypes[1].Descriptor()
}

func (Track_TrackType) Type() protoreflect.EnumType {
	return &file_godiscogs_proto_enumTypes[1]
}

func (x Track_TrackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Track_TrackType.Descriptor instead.
func (Track_TrackType) EnumDescriptor() ([]byte, []int) {
	return file_godiscogs_proto_rawDescGZIP(), []int{8, 0}
}

type ForSale struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the record
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The id of the sale
	SaleId int64 `protobuf:"varint,2,opt,name=sale_id,json=saleId,proto3" json:"sale_id,omitempty"`
	// The current price
	SalePrice     int32 `protobuf:"varint,3,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	DatePosted    int64 `protobuf:"varint,4,opt,name=date_posted,json=datePosted,proto3" json:"date_posted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForSale) Reset() {
	*x = ForSale{}
	mi := &file_godiscogs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForSale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForSale) ProtoMessage() {}

func (x *ForSale) ProtoReflect() protoreflect.Message {
	mi := &file_godiscogs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForSale.ProtoReflect.Descriptor instead.
func (*ForSale) Descriptor() ([]byte, []int) {
	return file_godiscogs_proto_rawDescGZIP(), []int{0}
}

func (x *ForSale) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ForSale) GetSaleId() int64 {
	if x != nil {
		return x.SaleId
	}
	return 0
}

func (x *ForSale) GetSalePrice() int32 {
	if x != nil {
		return x.SalePrice
	}
	return 0
}

func (x *ForSale) GetDatePosted() int64 {
	if x != nil {
		return x.DatePosted
	}
	return 0
}

type Label struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the label
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The catalogue number
	Catno string `protobuf:"bytes,2,opt,name=catno,proto3" json:"catno,omitempty"`
	// The id of the label
	Id            int32 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_godiscogs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_godiscogs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_godiscogs_proto_rawDescGZIP(), []int{1}
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetCatno() string {
	if x != nil {
		return x.Catno
	}
	return ""
}

func (x *Label) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Folder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id number of the folder
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the folder
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_godiscogs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_godiscogs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_godiscogs_proto_rawDescGZIP(), []int{2}
}

func (x *Folder) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Folder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Artist struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id number of the artist
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the artist
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artist) Reset() {
	*x = Artist{}
	mi := &file_godiscogs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_godiscogs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_godiscogs_proto_rawDescGZIP(), []int{3}
}

func (x *Artist) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Artist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Image struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The uri to the image
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// The type of image
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_godiscogs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_godiscogs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_godiscogs_proto_rawDescGZIP(), []int{4}
}

func (x *Image) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Image) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Format struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The descriptions of the Format
	Descriptions []string `protobuf:"bytes,1,rep,name=descriptions,proto3" json:"descriptions,omitempty"`
	// The name of the Format
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The number of the format
	Qty string `protobuf:"bytes,3,opt,name=qty,proto3" json:"qty,omitempty"`
	// Text associated with the Format
	Text          string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Format) Reset() {
	*x = Format{}
	mi := &file_godiscogs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Format) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Format) ProtoMessage() {}

func (x *Format) ProtoReflect() protoreflect.Message {
	mi := &file_godiscogs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Format.ProtoReflect.Descriptor instead.
func (*Format) Descriptor() ([]byte, []int) {
	return file_godiscogs_proto_rawDescGZIP(), []int{5}
}

func (x *Format) GetDescriptions() []string {
	if x != nil {
		return x.Descriptions
	}
	return nil
}

func (x *Format) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Format) GetQty() string {
	if x != nil {
		return x.Qty
	}
	return ""
}

func (x *Format) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Release struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id number of the release
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The title of the release
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Artists associated with the release
	Artists []*Artist `protobuf:"bytes,3,rep,name=artists,proto3" json:"artists,omitempty"`
	// The folder in which the record is stored
	FolderId int32 `protobuf:"varint,4,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	// Images associated with the release
	Images []*Image `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	// The instance id of this release
	InstanceId int32 `protobuf:"varint,6,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// The labels connected to this release
	Labels []*Label `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty"`
	// The number of discs in the release
	FormatQuantity int32 `protobuf:"varint,8,opt,name=format_quantity,json=formatQuantity,proto3" json:"format_quantity,omitempty"`
	// The rating given to this release
	Rating int32 `protobuf:"varint,9,opt,name=rating,proto3" json:"rating,omitempty"`
	// The earliest release date of this record
	EarliestReleaseDate int64 `protobuf:"varint,10,opt,name=earliest_release_date,json=earliestReleaseDate,proto3" json:"earliest_release_date,omitempty"`
	// The master ID of this release
	MasterId int32 `protobuf:"varint,11,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	// The release date of this release
	Released string `protobuf:"bytes,12,opt,name=released,proto3" json:"released,omitempty"`
	// The formats of the release
	Formats []*Format `protobuf:"bytes,13,rep,name=formats,proto3" json:"formats,omitempty"`
	// Is this a gatefold?
	Gatefold bool `protobuf:"varint,14,opt,name=gatefold,proto3" json:"gatefold,omitempty"`
	// Is this a boxset
	Boxset bool `protobuf:"varint,15,opt,name=boxset,proto3" json:"boxset,omitempty"`
	// The tracks for this release
	Tracklist       []*Track `protobuf:"bytes,16,rep,name=tracklist,proto3" json:"tracklist,omitempty"`
	InstanceNotes   []*Note  `protobuf:"bytes,19,rep,name=instance_notes,json=instanceNotes,proto3" json:"instance_notes,omitempty"`
	RecordCondition string   `protobuf:"bytes,17,opt,name=record_condition,json=recordCondition,proto3" json:"record_condition,omitempty"`
	SleeveCondition string   `protobuf:"bytes,18,opt,name=sleeve_condition,json=sleeveCondition,proto3" json:"sleeve_condition,omitempty"`
	DigitalVersions []int32  `protobuf:"varint,20,rep,packed,name=digital_versions,json=digitalVersions,proto3" json:"digital_versions,omitempty"`
	OtherVersions   []int32  `protobuf:"varint,21,rep,packed,name=other_versions,json=otherVersions,proto3" json:"other_versions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Release) Reset() {
	*x = Release{}
	mi := &file_godiscogs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Release) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Release) ProtoMessage() {}

func (x *Release) ProtoReflect() protoreflect.Message {
	mi := &file_godiscogs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Release.ProtoReflect.Descriptor instead.
func (*Release) Descriptor() ([]byte, []int) {
	return file_godiscogs_proto_rawDescGZIP(), []int{6}
}

func (x *Release) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Release) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Release) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *Release) GetFolderId() int32 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

func (x *Release) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Release) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *Release) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Release) GetFormatQuantity() int32 {
	if x != nil {
		return x.FormatQuantity
	}
	return 0
}

func (x *Release) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Release) GetEarliestReleaseDate() int64 {
	if x != nil {
		return x.EarliestReleaseDate
	}
	return 0
}

func (x *Release) GetMasterId() int32 {
	if x != nil {
		return x.MasterId
	}
	return 0
}

func (x *Release) GetReleased() string {
	if x != nil {
		return x.Released
	}
	return ""
}

func (x *Release) GetFormats() []*Format {
	if x != nil {
		return x.Formats
	}
	return nil
}

func (x *Release) GetGatefold() bool {
	if x != nil {
		return x.Gatefold
	}
	return false
}

func (x *Release) GetBoxset() bool {
	if x != nil {
		return x.Boxset
	}
	return false
}

func (x *Release) GetTracklist() []*Track {
	if x != nil {
		return x.Tracklist
	}
	return nil
}

func (x *Release) GetInstanceNotes() []*Note {
	if x != nil {
		return x.InstanceNotes
	}
	return nil
}

func (x *Release) GetRecordCondition() string {
	if x != nil {
		return x.RecordCondition
	}
	return ""
}

func (x *Release) GetSleeveCondition() string {
	if x != nil {
		return x.SleeveCondition
	}
	return ""
}

func (x *Release) GetDigitalVersions() []int32 {
	if x != nil {
		return x.DigitalVersions
	}
	return nil
}

func (x *Release) GetOtherVersions() []int32 {
	if x != nil {
		return x.OtherVersions
	}
	return nil
}

type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldId       int32                  `protobuf:"varint,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_godiscogs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_godiscogs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_godiscogs_proto_rawDescGZIP(), []int{7}
}

func (x *Note) GetFieldId() int32 {
	if x != nil {
		return x.FieldId
	}
	return 0
}

func (x *Note) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      string                 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type_         string                 `protobuf:"bytes,3,opt,name=type_,json=type,proto3" json:"type_,omitempty"`
	TrackType     Track_TrackType        `protobuf:"varint,4,opt,name=track_type,json=trackType,proto3,enum=godiscogs.Track_TrackType" json:"track_type,omitempty"`
	SubTracks     []*Track               `protobuf:"bytes,5,rep,name=sub_tracks,json=subTracks,proto3" json:"sub_tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_godiscogs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_godiscogs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_godiscogs_proto_rawDescGZIP(), []int{8}
}

func (x *Track) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Track) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Track) GetType_() string {
	if x != nil {
		return x.Type_
	}
	return ""
}

func (x *Track) GetTrackType() Track_TrackType {
	if x != nil {
		return x.TrackType
	}
	return Track_UNKNOWN
}

func (x *Track) GetSubTracks() []*Track {
	if x != nil {
		return x.SubTracks
	}
	return nil
}

var File_godiscogs_proto protoreflect.FileDescriptor

const file_godiscogs_proto_rawDesc = "" +
	"\n" +
	"\x0fgodiscogs.proto\x12\tgodiscogs\"r\n" +
	"\aForSale\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\asale_id\x18\x02 \x01(\x03R\x06saleId\x12\x1d\n" +
	"\n" +
	"sale_price\x18\x03 \x01(\x05R\tsalePrice\x12\x1f\n" +
	"\vdate_posted\x18\x04 \x01(\x03R\n" +
	"datePosted\"A\n" +
	"\x05Label\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05catno\x18\x02 \x01(\tR\x05catno\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\",\n" +
	"\x06Folder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\",\n" +
	"\x06Artist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"-\n" +
	"\x05Image\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"f\n" +
	"\x06Format\x12\"\n" +
	"\fdescriptions\x18\x01 \x03(\tR\fdescriptions\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\tR\x03qty\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\x8d\x06\n" +
	"\aRelease\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12+\n" +
	"\aartists\x18\x03 \x03(\v2\x11.godiscogs.ArtistR\aartists\x12\x1b\n" +
	"\tfolder_id\x18\x04 \x01(\x05R\bfolderId\x12(\n" +
	"\x06images\x18\x05 \x03(\v2\x10.godiscogs.ImageR\x06images\x12\x1f\n" +
	"\vinstance_id\x18\x06 \x01(\x05R\n" +
	"instanceId\x12(\n" +
	"\x06labels\x18\a \x03(\v2\x10.godiscogs.LabelR\x06labels\x12'\n" +
	"\x0fformat_quantity\x18\b \x01(\x05R\x0eformatQuantity\x12\x16\n" +
	"\x06rating\x18\t \x01(\x05R\x06rating\x122\n" +
	"\x15earliest_release_date\x18\n" +
	" \x01(\x03R\x13earliestReleaseDate\x12\x1b\n" +
	"\tmaster_id\x18\v \x01(\x05R\bmasterId\x12\x1a\n" +
	"\breleased\x18\f \x01(\tR\breleased\x12+\n" +
	"\aformats\x18\r \x03(\v2\x11.godiscogs.FormatR\aformats\x12\x1a\n" +
	"\bgatefold\x18\x0e \x01(\bR\bgatefold\x12\x16\n" +
	"\x06boxset\x18\x0f \x01(\bR\x06boxset\x12.\n" +
	"\ttracklist\x18\x10 \x03(\v2\x10.godiscogs.TrackR\ttracklist\x126\n" +
	"\x0einstance_notes\x18\x13 \x03(\v2\x0f.godiscogs.NoteR\rinstanceNotes\x12)\n" +
	"\x10record_condition\x18\x11 \x01(\tR\x0frecordCondition\x12)\n" +
	"\x10sleeve_condition\x18\x12 \x01(\tR\x0fsleeveCondition\x12)\n" +
	"\x10digital_versions\x18\x14 \x03(\x05R\x0fdigitalVersions\x12%\n" +
	"\x0eother_versions\x18\x15 \x03(\x05R\rotherVersions\"7\n" +
	"\x04Note\x12\x19\n" +
	"\bfield_id\x18\x01 \x01(\x05R\afieldId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xec\x01\n" +
	"\x05Track\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\tR\bposition\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x13\n" +
	"\x05type_\x18\x03 \x01(\tR\x04type\x129\n" +
	"\n" +
	"track_type\x18\x04 \x01(\x0e2\x1a.godiscogs.Track.TrackTypeR\ttrackType\x12/\n" +
	"\n" +
	"sub_tracks\x18\x05 \x03(\v2\x10.godiscogs.TrackR\tsubTracks\"0\n" +
	"\tTrackType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05TRACK\x10\x01\x12\v\n" +
	"\aHEADING\x10\x02*T\n" +
	"\tSaleState\x12\x10\n" +
	"\fNOT_FOR_SALE\x10\x00\x12\f\n" +
	"\bFOR_SALE\x10\x01\x12\b\n" +
	"\x04SOLD\x10\x02\x12\v\n" +
	"\aEXPIRED\x10\x03\x12\x10\n" +
	"\fSOLD_OFFLINE\x10\x04B)Z'github.com/brotherlogic/godiscogs/protob\x06proto3"

var (
	file_godiscogs_proto_rawDescOnce sync.Once
	file_godiscogs_proto_rawDescData []byte
)

func file_godiscogs_proto_rawDescGZIP() []byte {
	file_godiscogs_proto_rawDescOnce.Do(func() {
		file_godiscogs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_godiscogs_proto_rawDesc), len(file_godiscogs_proto_rawDesc)))
	})
	return file_godiscogs_proto_rawDescData
}

var file_godiscogs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_godiscogs_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_godiscogs_proto_goTypes = []any{
	(SaleState)(0),       // 0: godiscogs.SaleState
	(Track_TrackType)(0), // 1: godiscogs.Track.TrackType
	(*ForSale)(nil),      // 2: godiscogs.ForSale
	(*Label)(nil),        // 3: godiscogs.Label
	(*Folder)(nil),       // 4: godiscogs.Folder
	(*Artist)(nil),       // 5: godiscogs.Artist
	(*Image)(nil),        // 6: godiscogs.Image
	(*Format)(nil),       // 7: godiscogs.Format
	(*Release)(nil),      // 8: godiscogs.Release
	(*Note)(nil),         // 9: godiscogs.Note
	(*Track)(nil),        // 10: godiscogs.Track
}
var file_godiscogs_proto_depIdxs = []int32{
	5,  // 0: godiscogs.Release.artists:type_name -> godiscogs.Artist
	6,  // 1: godiscogs.Release.images:type_name -> godiscogs.Image
	3,  // 2: godiscogs.Release.labels:type_name -> godiscogs.Label
	7,  // 3: godiscogs.Release.formats:type_name -> godiscogs.Format
	10, // 4: godiscogs.Release.tracklist:type_name -> godiscogs.Track
	9,  // 5: godiscogs.Release.instance_notes:type_name -> godiscogs.Note
	1,  // 6: godiscogs.Track.track_type:type_name -> godiscogs.Track.TrackType
	10, // 7: godiscogs.Track.sub_tracks:type_name -> godiscogs.Track
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_godiscogs_proto_init() }
func file_godiscogs_proto_init() {
	if File_godiscogs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_godiscogs_proto_rawDesc), len(file_godiscogs_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_godiscogs_proto_goTypes,
		DependencyIndexes: file_godiscogs_proto_depIdxs,
		EnumInfos:         file_godiscogs_proto_enumTypes,
		MessageInfos:      file_godiscogs_proto_msgTypes,
	}.Build()
	File_godiscogs_proto = out.File
	file_godiscogs_proto_goTypes = nil
	file_godiscogs_proto_depIdxs = nil
}
